version: "3"

services:
  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    ports:
      - "9999:9999"
    volumes:
      - influxdb-vol:/root/.influxdbv2

volumes:
  influxdb-vol:
